### ISSUE TITLE
Help in using.

### ISSUE THREAD

**Issue by tracer-code** [cleeque/boomstream-downloader#4]
Hello)
I am just a beginner programmer and have not touched on the web part (Headings, etc.) yet.

Could you help me?)

I cannot understand the pin parameter.

I would be very grateful if you could take me by the handle once in using your program.

I have a link to a stream of this kind - https://play.boomstream.com/geNUkaGX?ppv=6dwUEIkA

I looked at the 1 .ts file and its header from where it is loaded. - https://m10.boomstream.com/vod/hash:b627c8dd4ac7c58b25f8194d44ca1f13/id:21403.22095.560092.32011803.113422.hls/time:0/data:eyJwcHYiOiI2ZHdVRUlrQSIsInVzZV9kaXJlY3RfbGlua3MiOiJ5ZXMiLCJpc19lbmNyeXB0IjoieWVzIn0=/m59/2021/01/21/Y1oJMU5X.mp4/media- 1.ts

Please help me create a command exclusively for me to use the program.
I apologize again !!!
I'm too inexperienced for now.

And it seems to me that it would be appropriate to record a video, with a full cycle from receiving tokens to downloading video.
A lot of people would be attracted to their repository)

**Comment by tracer-code** [comment]
```
(env) C:\Users\****\Desktop\env>py boom.py --url https://play.boomstream.com/geNUkaGX?ppv=6dwUEIkA --pin 29fba832-3c2a-4244-af4e-e4f1b2458e83   
Traceback (most recent call last):
  File "C:\Users\exCODE\Desktop\env\boom.py", line 269, in <module>
    sys.exit(app.run())
  File "C:\Users\exCODE\Desktop\env\boom.py", line 243, in run
    if len(self.config['mediaData']['records']) == 0:
KeyError: 'records'
```
I may not indicate it like that.
I downloaded the html page with a video player.
How to download the video itself in one file?
